"""
models/social_post.py

Defines the SocialPost data model.

A SocialPost is one finished, ready-to-review social media post.
It is produced by Phase 5 (caption_agent) and carries everything
needed for the founder to review it and eventually export it to CSV.

One SocialPost maps to one TranscriptMoment.
The caption is always grounded in the verbatim quote from that moment.

Phase 6 (csv_export) reads a list of SocialPost objects and formats
them into the scheduler-ready CSV using the exact column names from
the uploaded sample CSV.
"""

import json
from dataclasses import dataclass, field, asdict
from pathlib import Path
from typing import List


@dataclass
class Hashtags:
    """
    Three-tier hashtag set for one post.

    Tier 1 — niche tags under 100K posts. Most targeted.
    Tier 2 — mid-range tags 100K–1M posts.
    Tier 3 — broad tags over 1M posts. Max 2.
    """
    tier1_niche: List[str] = field(default_factory=list)
    tier2_midrange: List[str] = field(default_factory=list)
    tier3_broad: List[str] = field(default_factory=list)

    def all_tags(self) -> List[str]:
        """Return all tags as a single flat list, tier 1 first."""
        return self.tier1_niche + self.tier2_midrange + self.tier3_broad

    def formatted(self) -> str:
        """Return all tags as a space-separated string for the CSV."""
        return " ".join(self.all_tags())

    def to_dict(self) -> dict:
        return asdict(self)


@dataclass
class SocialPost:
    """
    One complete, ready-to-review social media post.

    Produced by Phase 5 (caption_agent).
    Read by Phase 6 (csv_export_agent).

    CSV column mapping (matches the uploaded sample CSV exactly):
        postAtSpecificTime  ← scheduled_date + scheduled_time
        content +Hashtags   ← caption + "\n\n" + hashtags.formatted()
        link (OGmetaUrl)    ← cta_link
        imageUrls           ← image_url (blank until Phase 7+)
        gifUrl              ← always blank
        videoUrls           ← clip_url
    """

    # ── Identity ──────────────────────────────────────────────────
    post_index: int = 0
    # Position in the campaign post list (0-based)

    source_moment_index: int = 0
    # Which TranscriptMoment this post came from

    # ── Core content ──────────────────────────────────────────────
    platform: str = ""
    # e.g. "LinkedIn", "Instagram", "Twitter/X"

    content_pillar: str = ""
    # Exact pillar name from MessageDNA — carried through from the moment

    caption: str = ""
    # The full post caption in the founder's voice.
    # Includes the transcript quote, context, and CTA.
    # Does NOT include hashtags — those are in the hashtags field.

    hashtags: Hashtags = field(default_factory=Hashtags)
    # Three-tier hashtag set

    # ── Source grounding ──────────────────────────────────────────
    transcript_quote: str = ""
    # The verbatim quote from the TranscriptMoment that this post is built on.
    # Copied exactly — never modified.

    clip_url: str = ""
    # YouTube timestamp URL for the source moment (blank for manual transcripts)

    start_timestamp: str = ""
    end_timestamp: str = ""

    # ── Scheduling ────────────────────────────────────────────────
    scheduled_date: str = ""
    # YYYY-MM-DD or blank

    scheduled_time: str = ""
    # HH:MM (24-hour) or blank

    # ── Assets ────────────────────────────────────────────────────
    cta_link: str = ""
    # The URL from CampaignBrief — goes into link (OGmetaUrl) column

    image_prompt: str = ""
    # The Imagen prompt generated by image_prompt_agent (Phase 6A).
    # Blank until Phase 6A runs. Saved to JSON so it can be inspected
    # or reused if image regeneration is needed.

    image_url: str = ""
    # Local file path (data/images/post_001.png) set by Phase 6A.
    # Replaced with a Cloud Storage https:// URL in production.
    # Goes into the imageUrls column of the CSV.

    # ── Review status ─────────────────────────────────────────────
    status: str = "draft"
    # "draft" | "approved" | "rejected"
    # Phase 6 only exports posts with status == "approved"

    review_notes: str = ""
    # Founder's notes during review (optional)

    def content_and_hashtags(self) -> str:
        """
        Returns the combined content + hashtags string.
        This is what goes in the 'content +Hashtags' CSV column.
        """
        tags = self.hashtags.formatted()
        if tags:
            return f"{self.caption}\n\n{tags}"
        return self.caption

    def scheduled_datetime(self) -> str:
        """
        Returns the scheduled datetime string for the CSV.
        Format: YYYY-MM-DD HH:MM:SS
        Returns blank string if neither date nor time is set.
        """
        if self.scheduled_date and self.scheduled_time:
            return f"{self.scheduled_date} {self.scheduled_time}:00"
        return ""

    def to_dict(self) -> dict:
        d = asdict(self)
        return d

    def summary_line(self) -> str:
        """One-line summary for terminal display."""
        q = self.transcript_quote[:50] + "..." if len(self.transcript_quote) > 50 else self.transcript_quote
        return (
            f"Post {self.post_index + 1} | {self.platform} | "
            f"{self.content_pillar[:40]} | \"{q}\""
        )


@dataclass
class CaptionResult:
    """
    The complete output of Phase 5 — all posts for one campaign.
    """
    campaign_id: str = ""
    posts: List[SocialPost] = field(default_factory=list)
    generation_notes: str = ""
    # Agent notes about voice consistency, any warnings, pillar coverage

    @property
    def total_posts(self) -> int:
        return len(self.posts)

    def approved_posts(self) -> List[SocialPost]:
        return [p for p in self.posts if p.status == "approved"]

    def to_dict(self) -> dict:
        return {
            "campaign_id": self.campaign_id,
            "total_posts": self.total_posts,
            "generation_notes": self.generation_notes,
            "posts": [p.to_dict() for p in self.posts],
        }

    def to_json(self, indent: int = 2) -> str:
        return json.dumps(self.to_dict(), indent=indent)

    @classmethod
    def from_dict(cls, data: dict) -> "CaptionResult":
        posts = []
        for p in data.get("posts", []):
            hashtags_data = p.pop("hashtags", {})
            # Backward compatibility: posts saved before Phase 6A won't have image_prompt
            p.setdefault("image_prompt", "")
            post = SocialPost(**p)
            post.hashtags = Hashtags(**hashtags_data)
            posts.append(post)
        result = cls(
            campaign_id=data.get("campaign_id", ""),
            generation_notes=data.get("generation_notes", ""),
        )
        result.posts = posts
        return result

    def summary(self) -> str:
        if not self.posts:
            return "No posts generated."
        platform_counts: dict = {}
        for p in self.posts:
            platform_counts[p.platform] = platform_counts.get(p.platform, 0) + 1
        platform_str = ", ".join(f"{k} ({v})" for k, v in platform_counts.items())
        return (
            f"✅ {self.total_posts} posts generated | {platform_str}"
        )


def save_caption_result(result: CaptionResult, filepath: str) -> None:
    """Save a CaptionResult to JSON."""
    Path(filepath).parent.mkdir(parents=True, exist_ok=True)
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(result.to_json())
    print(f"✅ Posts saved to: {filepath}")


def load_caption_result(filepath: str) -> CaptionResult:
    """Load a CaptionResult from JSON."""
    with open(filepath, "r", encoding="utf-8") as f:
        data = json.load(f)
    result = CaptionResult.from_dict(data)
    print(f"✅ Posts loaded from: {filepath}")
    return result
